SELECT DISTINCT
	POL.POLICYNUMBER 'POL_NUM',
	EC.CONTRACTNUMBER 'CONTRACT_NUM',
	EC.ID 'CONTRACT_ID',
	ET.ID 'ENROLL_TRAN',
	POL.PEOPLESOFTCLIENTNUMBER 'PS_NUM',
	CAST(ECP.COVERAGESTARTDATE AS DATE) 'COV_START',
	CAST(ECP.COVERAGEENDDATE AS DATE) 'COV_END',
	CASE	WHEN EALF.PCMUSAGECODEID = '128' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME 
			WHEN EALF.PCMUSAGECODEID = '128' AND PSCONF.NAME IS NOT NULL THEN PSCONF.NAME 
			WHEN EALF.PCMUSAGECODEID = '32' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME ELSE NULL END 'SETTLEMENT',
	CAST(	PROD.CODE AS INT) 'PRODUCT',
	ECU.CUSTOMERNAME 'CUSTOMER_NAME',
	EA.ADDRESS1+(CASE WHEN EA.ADDRESS2 IS NULL THEN '' ELSE (' '+EA.ADDRESS2) END) 'CUSTOMER_ADD',
	EA.CITY 'CUSTOMER_CITY',
	EA.STATE 'CUSTOMER_STATE',
	EA.POSTALCODE 'CUSTOMER_ZIP',
	ECU.CUSTOMERPHONE 'CUSTOMER_PHONE',
	ECU.CUSTOMEREMAILADDRESS 'CUSTOMER_EMAIL',
	ECP.COVERAGEPERIOD 'COVERAGE_PERIOD',
	CAST(EA.DATECREATED AS DATE) 'CUSTOMER_CREATE',
	CAST(EA.UPDATED AS DATE) 'CUSTOMER_EDIT',
	CAST(EC.DATECREATED AS DATE) 'CONTRACT_CREATE',
	CAST(EC.UPDATED AS DATE) 'CONTRACT_EDIT',
	CAST(E.DATECREATED AS DATE) 'ENROLL_CREATE',
	CAST(E.UPDATED AS DATE) 'ENROLL_EDIT',
	CAST(ECP.DATECREATED AS DATE) 'COV_CREATE',
	CAST(ECP.UPDATED AS DATE) 'COV_EDIT'

FROM		SESENROLLMENTPRODCOPY.DBO.ENROLLMENT E
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTCONTRACT EC ON			(	E.ENROLLMENTCONTRACTID = EC.ID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTCUSTOMER ECU ON			(	E.ENROLLMENTCUSTOMERID = ECU.ID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP ON	(	E.ID = ECP.ENROLLMENTID AND																			
																			ECP.ID = (SELECT MAX(ECP2.ID) FROM SESENROLLMENTPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP2 WHERE ECP2.ENROLLMENTID = E.ID))
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTTRANS ET ON				(	ET.ENROLLMENTCOVERAGEPERIODID = ECP.ID AND
																			ET.ID = (SELECT MAX(ET2.ID) FROM SESENROLLMENTPRODCOPY.DBO.ENROLLMENTTRANS ET2 WHERE ET2.ENROLLMENTCOVERAGEPERIODID = ECP.ID) and ET.TRANSACTIONTYPEID = '1')
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTADDRESS EA ON			(	ET.ENROLLMENTADDRESSID = EA.ID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTPCMPOLICY PCM ON		(	PCM.ENROLLMENTTRANSID = ET.ID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTASSETLIST EAL ON		(	ET.ID = EAL.ENROLLMENTTRANSID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTASSETLISTFACTOR EALF ON	(	EALF.ENROLLMENTASSETLISTID = EAL.ID AND
																			EALF.PCMCONTAINERID = PCM.PCMCONTAINERID AND
																			EALF.PCMPOLICYSCHEMAID = PCM.PCMPOLICYSCHEMAID AND
																			EALF.PCMPOLICYID = PCM.PCMPOLICYID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICY POL ON							(	PCM.PCMPOLICYID = POL.ID)
INNER JOIN  SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH ON						(	SCH.POLICYID = PCM.PCMPOLICYID AND
																			SCH.ID = PCM.PCMPOLICYSCHEMAID)
INNER JOIN  SESHOSTPRODCOPY.DBO.MASTERPRODUCT PROD ON					(	PROD.ID = SCH.PRODUCTID AND PROD.CODE in ('2310'))
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMACOVERAGEFACTOR PSCOVF ON	(	PSCOVF.COVERAGEFACTORHEADERID = EALF.PCMHEADERID AND 
																			PSCOVF.ID = EALF.PCMFACTORID AND 
																			PSCOVF.USAGECODEID = EALF.PCMUSAGECODEID AND 
																			PSCOVF.ISSELECTED = '1')
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMACONTAINERFACTOR PSCONF ON	(	PSCONF.CONTAINERFACTORHEADERID = EALF.PCMHEADERID AND
																			PSCONF.ID = EALF.PCMFACTORID AND 
																			PSCONF.USAGECODEID = EALF.PCMUSAGECODEID AND
																			PSCONF.ISSELECTED = '1')

WHERE (CASE WHEN EALF.PCMUSAGECODEID = '128' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME 
			WHEN EALF.PCMUSAGECODEID = '128' AND PSCONF.NAME IS NOT NULL THEN PSCONF.NAME 
			WHEN EALF.PCMUSAGECODEID = '32' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME ELSE NULL END) IS NOT NULL


GROUP BY 
	EC.ID,
	PROD.CODE,
	ECU.CUSTOMERNAME,
	EA.ADDRESS1+(CASE WHEN EA.ADDRESS2 IS NULL THEN '' ELSE (' '+EA.ADDRESS2) END),
	EA.CITY,
	EA.STATE,
	EA.POSTALCODE,
	ECU.CUSTOMERPHONE,
	ECU.CUSTOMEREMAILADDRESS,
	CAST(EA.DATECREATED AS DATE),
	CAST(EA.UPDATED AS DATE),
	EC.CONTRACTNUMBER,
	ECP.COVERAGEPERIOD,
	CAST(EC.DATECREATED AS DATE),
	CAST(EC.UPDATED AS DATE),
	POL.POLICYNUMBER,
	POL.PEOPLESOFTCLIENTNUMBER,
	CAST(E.DATECREATED AS DATE),
	CAST(E.UPDATED AS DATE),
	CAST(ECP.COVERAGESTARTDATE AS DATE),
	CAST(ECP.COVERAGEENDDATE AS DATE),
	CAST(ECP.DATECREATED AS DATE),
	CAST(ECP.UPDATED AS DATE),		
	ET.ID,
	ET.BILLINGFREQUENCY,
	EALF.PCMUSAGECODEID,
	PSCOVF.NAME,
	PSCONF.NAME

order by EC.ID