WITH DATA_EXTRACT AS (

SELECT 
E.ID 'EnrollmentID',
CP.ID 'CoveragePeriodID',
A.ID 'AssetID',
B.ID 'BatchID',
E.CONTRACTNUMBER 'ContractNumber',
E.POLICYNUMBER 'PolicyNumber',
E.RENTALREFERENCEID 'RentalReferenceID',
E.CUSTOMERNAME 'CustomerName',
E.ADDRESSLINE1+(CASE WHEN E.ADDRESSLINE2 IS NULL THEN '' ELSE (' '+E.ADDRESSLINE2) END) 'CUSTOMER_ADD',
E.CITY 'City',
E.STATE 'State',
E.ZIP 'Zipcode',
REPLACE(A.ASSETDESCRIPTION, '"', '') 'Asset Decription',
--Need to replace special characters, non-printing characters in description as it may create corrupted data
A.ASSETVALUE 'Asset Value',
A.GAIASSETCLASS 'Asset Class',
MC.NAME 'Class Name',
A.RENTALAMOUNT 'Rental Amount',
A.DEDUCTIBLE 'Deductible',
--CONVERT(INT,COALESCE(NULLIF(REPLACE(REPLACE(A.DEDUCTIBLE, '.00', ''), ' ', '500'), ''), '800')) AS 'Deductible',
CAST (A.RENTALSTARTDATE AS DATE) 'Rental Start Date',
CAST (A.RENTALENDDATE AS DATE) 'Rental End Date',
A.DAYSOFCOVERAGE 'Days of Coverage',
(DATEDIFF(DAY, A.RENTALSTARTDATE, A.RENTALENDDATE)+1) AS 'NEW_COVERAGE DAYS',
--CP.DAYSOFCOVERAGE 'Days of Coverage',
CASE
		WHEN DATEDIFF(DAY, A.RENTALSTARTDATE, A.RENTALENDDATE) >= 30 THEN 'Monthly Rate'
		WHEN DATEDIFF(DAY, A.RENTALSTARTDATE, A.RENTALENDDATE) >= 7 THEN 'Weekly Rate'
		ELSE 'Daily Rate'
	END AS 'NEW_RATE TYPE',
A.MONTHLYPREMIUM 'Reported Premium',
CASE
		WHEN DATEDIFF(DAY, A.RENTALSTARTDATE, A.RENTALENDDATE) >= 30 THEN CAST(((A.MONTHLYPREMIUM/DATEDIFF(DAY, A.RENTALSTARTDATE, A.RENTALENDDATE))*30) AS DECIMAL (10,2))
		WHEN DATEDIFF(DAY, A.RENTALSTARTDATE, A.RENTALENDDATE) >= 7 THEN CAST(((A.MONTHLYPREMIUM/DATEDIFF(DAY, A.RENTALSTARTDATE, A.RENTALENDDATE))*7) AS DECIMAL (10,2))
		ELSE CAST(A.MONTHLYPREMIUM/(ABS(DATEDIFF(DAY, A.RENTALSTARTDATE, A.RENTALENDDATE))+1) AS DECIMAL(10,2))
	END AS 'NEW_PREMIUM RATE'

/* NEED TO CREATE THREE NEW COLUMNS
	ONE TO CALCULATE DAYS OF COVERAGE BETWEEN RENTAL START AND RENTAL END, THIS QUERY MAY HAVE TO BE PUT INTO THE WHERE STATEMENT AND HAVE THE SELECT STATEMENT INPUT CP.COVERAGEDAYS
		ALTER TABLE SESBATCHPRODCOPY.DBO.BAMCOVERAGEPERIOD ADD COVERAGEDAYS AS CAST(CP.RENTALENDDATE - CP.RENTALSTARTDATE AS NUMERIC (9,0))
		DATEDIFF (CP.RENTALENDDATE, CP.RENTALSTARTDATE) AS COVERAGEDAYS #MySQL requires two arguments, SQL Server requires 3 */

/* ONE TO BUCKET DAYS OF COVERAGE INTO DAILY RATE, WEEKLY RATE, MONTHLY RATE CALLED 'RATE TYPE'
	CASE
		WHEN CP.COVERAGEDAYS > 30 THEN 'Monthly Rate'
		WHEN CP.COVERAGEDAYS > 7 THEN 'Weekly Rate'
		ELSE 'Daily Rate'
	END AS 'Rate Type' */

/* ONE TO CALCULATE PREMIUM RATE BY 'RATE TYPE'; IN WHICH DAILY RATE WILL BE PREMIUM/DAYSOFCOVERAGE, WEEKLY RATE WILL BE PREMIUM/7, MONTHLY RATE WILL BE PREMIUM/30
	CASE
		WHEN RATETYPE = 'Weekly Rate' THEN (B.ORIGINALPREMIUMAMOUNT/7)
		WHEN RATETYPE = 'Monthly Rate' THEN (B.ORIGINALPREMIUMAMOUNT/30)
		ELSE (B.ORIGINALPREMIUMAMOUNT/A.DAYSOFCOVERAGE)
	END AS 'Premium Rate' */

FROM		SESBATCHPRODCOPY.DBO.BAMENROLLMENT E
INNER JOIN	SESBATCHPRODCOPY.DBO.BAMCOVERAGEPERIOD CP ON	(E.ID = CP.ENROLLMENTID)
INNER JOIN	SESBATCHPRODCOPY.DBO.BAMASSET A ON				(CP.ID = A.COVERAGEPERIODID)
LEFT JOIN	SESBATCHPRODCOPY.DBO.BATCH B ON					(B.ID = E.SOURCEBATCHID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.MASTERASSETCLASS MC ON		(A.GAIASSETCLASS = MC.CODE)
/* STILL TRYING TO FIGURE OUT HOW TO ADD PRODUCT CODE INTO THE TABLE SO THAT EVERYTHING ATTACHED IS PROD.CODE '2370' OR '2360'
ALSO TRYING TO FIGURE OUT WHERE THE RENTAL ENROLLMENTS FOR ASSET CLASS V1-V9 ARE AT */

WHERE	A.GAIASSETCLASS IS NOT NULL
AND		A.DAYSOFCOVERAGE IS NOT NULL
AND		B.ORIGINALPREMIUMAMOUNT <> 0
AND		A.DAYSOFCOVERAGE > 0
AND		(A.ASSETVALUE <> 0 AND CP.RENTALAMOUNT <> 0)

/*IDENTIFY KWIPPED POLICIES AND EXCLUDE FROM RETURN SETGroup by contract by everything, but make sure that Group by Rental Start Date and Rental End Date, Sum up Rental Amount, if Rental amount is negative then that means there was a
cancel with no coverage placement.

If there are lots of these enrollments then we need to address it possibly by making premium reported absolute but if not we can discuss further
If it shows 2-3% of the enrollments then its worth fixing*/
)

SELECT 
	EnrollmentID,
	CoveragePeriodID,
	BatchID,
	ContractNumber,
	PolicyNumber,
	RentalReferenceID,
	CustomerName,
	CUSTOMER_ADD,
	City,
	State,
	Zipcode, 
	[Asset Decription], 
	[Asset Value], 
	[Asset Class], 
	[Class Name], 
	[Rental Amount], 
	[Rental Start Date], 
	[Rental End Date], 
	[Days of Coverage], 
	[NEW_COVERAGE DAYS],
	CONVERT(INT,
		COALESCE(
			NULLIF(
				REPLACE(
					REPLACE(Deductible, '.00', ''), ' ', '500'), ''), '800')) AS 'Deductible',
	[NEW_RATE TYPE],
	[Reported Premium],
	[NEW_PREMIUM RATE]

FROM DATA_EXTRACT

GROUP BY
	EnrollmentID,
	CoveragePeriodID,
	BatchID,
	ContractNumber,
	PolicyNumber,
	RentalReferenceID,
	CustomerName,
	CUSTOMER_ADD,
	City,
	State,
	Zipcode, 
	[Asset Decription], 
	[Asset Value], 
	[Asset Class], 
	[Class Name], 
	[Rental Amount], 
	[Rental Start Date], 
	[Rental End Date], 
	[Days of Coverage], 
	[NEW_COVERAGE DAYS],
	Deductible,
	[NEW_RATE TYPE],
	[Reported Premium],
	[NEW_PREMIUM RATE]

ORDER BY	[Asset Class], [Rental Start Date]