SELECT
	POL.POLICYNUMBER 'Policy#',
	EC.CONTRACTNUMBER 'Contract Number',
	CAST(ECP.COVERAGESTARTDATE AS DATE) 'Coverage Start Date',
	CAST(ECP.COVERAGEENDDATE AS DATE) 'Coverage End Date',
	ECE.[CoverageStatus],
	year(CAST(ECP.COVERAGESTARTDATE AS DATE)) 'Policy Year',
	CAST(	PROD.CODE AS INT) 'ProductID',
	ET.TRANSACTIONTYPEID,
	ET.ID 'EnrollmentTransID',
	ECU.CUSTOMERNAME 'Customer Name',
	ECU.ADDRESS1+(CASE WHEN ECU.ADDRESS2 IS NULL THEN '' ELSE (' '+ECU.ADDRESS2) END) 'Customer Address',
	ECU.CITY 'Customer City',
	ECU.STATE 'Customer State',
	ECU.POSTALCODE 'Customer Zip',
	EA.AssetSerialVin 'Bicycle Serial#'


FROM		SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENT E
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCONTRACT EC ON (E.ENROLLMENTCONTRACTID = EC.ID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCUSTOMER ECU ON (E.ENROLLMENTCUSTOMERID = ECU.ID)
LEFT JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP ON (E.ID = ECP.ENROLLMENTID)
LEFT JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTTRANS ET ON (ET.ENROLLMENTCOVERAGEPERIODID = ECP.ID)
LEFT JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTPCMPOLICY PCM ON (PCM.ENROLLMENTTRANSID = ET.ID)
LEFT JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTASSETLIST EAL ON	(ET.ID = EAL.ENROLLMENTTRANSID)
LEFT JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTASSET EA ON	(EA.EnrollmentAssetListId = EAL.ID)
LEFT JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTASSETLISTFACTOR EALF ON (EALF.ENROLLMENTASSETLISTID = EAL.ID AND
																			EALF.PCMCONTAINERID = PCM.PCMCONTAINERID AND
																			EALF.PCMPOLICYSCHEMAID = PCM.PCMPOLICYSCHEMAID AND
																			EALF.PCMPOLICYID = PCM.PCMPOLICYID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICY POL ON								(	PCM.PCMPOLICYID = POL.ID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYINSURED POI ON						(	POL.INSUREDID = POI.ID)

LEFT JOIN  SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH ON							(	SCH.POLICYID = PCM.PCMPOLICYID AND
																				SCH.ID = PCM.PCMPOLICYSCHEMAID)
LEFT JOIN  SESHOSTPRODCOPY.DBO.MASTERPRODUCT PROD ON						(	PROD.ID = SCH.PRODUCTID)
LEFT JOIN [SESSearchProdCopy].[dbo].[EnrollmentCoverageElement] ECE on (E.ID = ECE.[EnrollmentId] and E.QuoteId = ECE.QuoteId)