	SELECT DISTINCT
	POL.POLICYNUMBER 'POL_NUM',
	CASE WHEN POL.APPLICATIONUSAGEID = '1' THEN 'BAM'
		WHEN POL.APPLICATIONUSAGEID = '2' THEN 'QIPS'
		WHEN POL.APPLICATIONUSAGEID = '3' THEN 'VES'
		WHEN POL.APPLICATIONUSAGEID = '4' THEN 'SED' END AS 'SYSTEM',
	EC.CONTRACTNUMBER 'CONTRACT_NUM',
	EC.ID 'CONTRACT_ID',
	ET.ID 'ENROLL_TRAN',
	POL.PEOPLESOFTCLIENTNUMBER 'PS_NUM',
	CAST(ECP.COVERAGESTARTDATE AS DATE) 'COV_START',
	CAST(ECP.COVERAGEENDDATE AS DATE) 'COV_END',
	CASE	WHEN EALF.PCMUSAGECODEID = '128' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME 
			WHEN EALF.PCMUSAGECODEID = '128' AND PSCONF.NAME IS NOT NULL THEN PSCONF.NAME 
			WHEN EALF.PCMUSAGECODEID = '32' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME ELSE NULL END 'SETTLEMENT',
	CAST(PROD.CODE AS INT) 'PRODUCT',
	ECU.CUSTOMERNAME 'CUSTOMER_NAME',
	ECU.ADDRESS1+(CASE WHEN ECU.ADDRESS2 IS NULL THEN '' ELSE (' '+ECU.ADDRESS2) END) 'CUSTOMER_ADD',
	ECU.CITY 'CUSTOMER_CITY',
	ECU.STATE 'CUSTOMER_STATE',
	ECU.POSTALCODE 'CUSTOMER_ZIP',
	CASE WHEN PROD.CODE = '2310' THEN ECU.CITY WHEN PROD.CODE = '2360' THEN ECU.CITY ELSE POI.CITY END 'INSURED_CITY',
	CASE WHEN PROD.CODE = '2310' THEN ECU.STATE  WHEN PROD.CODE = '2360' THEN ECU.STATE ELSE POI.STATEPROVINCE END 'INSURED_STATE',
	CASE WHEN PROD.CODE = '2310' THEN ECU.POSTALCODE  WHEN PROD.CODE = '2360' THEN ECU.POSTALCODE ELSE POI.POSTALCODE END 'INSURED_ZIP',
	ECU.CUSTOMERPHONE 'CUSTOMER_PHONE',
	ECU.CUSTOMEREMAILADDRESS 'CUSTOMER_EMAIL',
	ECP.COVERAGEPERIOD 'COVERAGE_PERIOD',
	CAST(ECU.DATECREATED AS DATE) 'CUSTOMER_CREATE',
	CAST(ECU.UPDATED AS DATE) 'CUSTOMER_EDIT',
	CAST(EC.DATECREATED AS DATE) 'CONTRACT_CREATE',
	CAST(EC.UPDATED AS DATE) 'CONTRACT_EDIT',
	CAST(E.DATECREATED AS DATE) 'ENROLL_CREATE',
	CAST(E.UPDATED AS DATE) 'ENROLL_EDIT',
	CAST(ECP.DATECREATED AS DATE) 'COV_CREATE',
	CAST(ECP.UPDATED AS DATE) 'COV_EDIT',
	CARR.NAME 'CARR_ABBR',
	CARR.DESCRIPTION 'CARR_NAME',
	CAST(PP.PRMCODE AS INT) 'PRODUCER_CODE'

FROM		SESENROLLMENTPRODCOPY.DBO.ENROLLMENT E
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTCONTRACT EC ON			(	E.ENROLLMENTCONTRACTID = EC.ID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTCUSTOMER ECU ON			(	E.ENROLLMENTCUSTOMERID = ECU.ID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP ON	(	E.ID = ECP.ENROLLMENTID AND
																			ECP.ID = (SELECT MAX(ECP2.ID) FROM SESENROLLMENTPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP2 WHERE ECP2.ENROLLMENTID = E.ID) AND
																			ECP.COVERAGEENDDATE > GETDATE())
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTTRANS ET ON				(	ET.ENROLLMENTCOVERAGEPERIODID = ECP.ID AND
																			ET.ID = (SELECT MAX(ET2.ID) FROM SESENROLLMENTPRODCOPY.DBO.ENROLLMENTTRANS ET2 WHERE ET2.ENROLLMENTCOVERAGEPERIODID = ECP.ID))
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTPCMPOLICY PCM ON		(	PCM.ENROLLMENTTRANSID = ET.ID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTASSETLIST EAL ON		(	ET.ID = EAL.ENROLLMENTTRANSID)
INNER JOIN	SESENROLLMENTPRODCOPY.DBO.ENROLLMENTASSETLISTFACTOR EALF ON	(	EALF.ENROLLMENTASSETLISTID = EAL.ID AND
																			EALF.PCMCONTAINERID = PCM.PCMCONTAINERID AND
																			EALF.PCMPOLICYSCHEMAID = PCM.PCMPOLICYSCHEMAID AND
																			EALF.PCMPOLICYID = PCM.PCMPOLICYID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICY POL ON							(	PCM.PCMPOLICYID = POL.ID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYINSURED POI ON					(	POL.INSUREDID = POI.ID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP ON					(	POL.ID = PP.POLICYID AND
																			PP.ID IN (SELECT MAX(PP2.ID) FROM SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP2 WHERE PP2.POLICYID = POL.ID))
INNER JOIN	SESHOSTPRODCOPY.DBO.NAICTYPE CARR ON						(	CARR.ID = POL.CARRIERID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH ON						(	SCH.POLICYID = PCM.PCMPOLICYID AND
																			SCH.ID = PCM.PCMPOLICYSCHEMAID) 
INNER JOIN	SESHOSTPRODCOPY.DBO.MASTERPRODUCT PROD ON					(	PROD.ID = SCH.PRODUCTID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMACOVERAGEFACTOR PSCOVF ON	(	PSCOVF.COVERAGEFACTORHEADERID = EALF.PCMHEADERID AND 
																			PSCOVF.ID = EALF.PCMFACTORID AND 
																			PSCOVF.USAGECODEID = EALF.PCMUSAGECODEID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMACONTAINERFACTOR PSCONF ON	(	PSCONF.CONTAINERFACTORHEADERID = EALF.PCMHEADERID AND
																			PSCONF.ID = EALF.PCMFACTORID AND 
																			PSCONF.USAGECODEID = EALF.PCMUSAGECODEID)
WHERE EALF.PCMUSAGECODEID IS NOT NULL
GROUP BY 
	EC.ID,
	POL.APPLICATIONUSAGEID,
	PROD.CODE,
	ECU.CUSTOMERNAME,
	ECU.ADDRESS1+(CASE WHEN ECU.ADDRESS2 IS NULL THEN '' ELSE (' '+ECU.ADDRESS2) END),
	ECU.CITY,
	ECU.STATE,
	ECU.POSTALCODE,
	POI.CITY,
	POI.STATEPROVINCE,
	POI.POSTALCODE,
	ECU.CUSTOMERPHONE,
	ECU.CUSTOMEREMAILADDRESS,
	CAST(ECU.DATECREATED AS DATE),
	CAST(ECU.UPDATED AS DATE),
	EC.CONTRACTNUMBER,
	ECP.COVERAGEPERIOD,
	CAST(EC.DATECREATED AS DATE),
	CAST(EC.UPDATED AS DATE),
	POL.POLICYNUMBER,
	POL.PEOPLESOFTCLIENTNUMBER,
	CAST(E.DATECREATED AS DATE),
	CAST(E.UPDATED AS DATE),
	CAST(ECP.COVERAGESTARTDATE AS DATE),
	CAST(ECP.COVERAGEENDDATE AS DATE),
	CAST(ECP.DATECREATED AS DATE),
	CAST(ECP.UPDATED AS DATE),		
	ET.ID,
	ET.BILLINGFREQUENCY,
	EALF.PCMUSAGECODEID,
	PSCOVF.NAME,
	PSCONF.NAME,
	CARR.NAME,
	CARR.DESCRIPTION,
	CAST(PP.PRMCODE AS INT)

union

SELECT DISTINCT
	POL.POLICYNUMBER 'POL_NUM',
	CASE WHEN POL.APPLICATIONUSAGEID = '1' THEN 'BAM'
		WHEN POL.APPLICATIONUSAGEID = '2' THEN 'QIPS'
		WHEN POL.APPLICATIONUSAGEID = '3' THEN 'VES'
		WHEN POL.APPLICATIONUSAGEID = '4' THEN 'SED' END AS 'SYSTEM',
	EC.CONTRACTNUMBER 'CONTRACT_NUM',
	EC.ID 'CONTRACT_ID',
	ET.ID 'ENROLL_TRAN',
	POL.PEOPLESOFTCLIENTNUMBER 'PS_NUM',
	CAST(ECP.COVERAGESTARTDATE AS DATE) 'COV_START',
	CAST(ECP.COVERAGEENDDATE AS DATE) 'COV_END',
	CASE	WHEN EALF.PCMUSAGECODEID = '128' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME 
			WHEN EALF.PCMUSAGECODEID = '128' AND PSCONF.NAME IS NOT NULL THEN PSCONF.NAME 
			WHEN EALF.PCMUSAGECODEID = '32' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME ELSE NULL END 'SETTLEMENT',
	CAST(PROD.CODE AS INT) 'PRODUCT',
	ECU.CUSTOMERNAME 'CUSTOMER_NAME',
	ECU.ADDRESS1+(CASE WHEN ECU.ADDRESS2 IS NULL THEN '' ELSE (' '+ECU.ADDRESS2) END) 'CUSTOMER_ADD',
	ECU.CITY 'CUSTOMER_CITY',
	ECU.STATE 'CUSTOMER_STATE',
	ECU.POSTALCODE 'CUSTOMER_ZIP',
	CASE WHEN PROD.CODE = '2310' THEN ECU.CITY WHEN PROD.CODE = '2360' THEN ECU.CITY ELSE POI.CITY END 'INSURED_CITY',
	CASE WHEN PROD.CODE = '2310' THEN ECU.STATE  WHEN PROD.CODE = '2360' THEN ECU.STATE ELSE POI.STATEPROVINCE END 'INSURED_STATE',
	CASE WHEN PROD.CODE = '2310' THEN ECU.POSTALCODE  WHEN PROD.CODE = '2360' THEN ECU.POSTALCODE ELSE POI.POSTALCODE END 'INSURED_ZIP',
	ECU.CUSTOMERPHONE 'CUSTOMER_PHONE',
	ECU.CUSTOMEREMAILADDRESS 'CUSTOMER_EMAIL',
	ECP.COVERAGEPERIOD 'COVERAGE_PERIOD',
	CAST(ECU.DATECREATED AS DATE) 'CUSTOMER_CREATE',
	CAST(ECU.UPDATED AS DATE) 'CUSTOMER_EDIT',
	CAST(EC.DATECREATED AS DATE) 'CONTRACT_CREATE',
	CAST(EC.UPDATED AS DATE) 'CONTRACT_EDIT',
	CAST(E.DATECREATED AS DATE) 'ENROLL_CREATE',
	CAST(E.UPDATED AS DATE) 'ENROLL_EDIT',
	CAST(ECP.DATECREATED AS DATE) 'COV_CREATE',
	CAST(ECP.UPDATED AS DATE) 'COV_EDIT',
	CARR.NAME 'CARR_ABBR',
	CARR.DESCRIPTION 'CARR_NAME',
	CAST(PP.PRMCODE AS INT) 'PRODUCER_CODE'

FROM		SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENT E
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCONTRACT EC ON			(	E.ENROLLMENTCONTRACTID = EC.ID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCUSTOMER ECU ON			(	E.ENROLLMENTCUSTOMERID = ECU.ID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP ON	(	E.ID = ECP.ENROLLMENTID AND
																				ECP.ID = (SELECT MAX(ECP2.ID) FROM SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP2 WHERE ECP2.ENROLLMENTID = E.ID) AND
																				ECP.COVERAGEENDDATE > GETDATE())
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTTRANS ET ON				(	ET.ENROLLMENTCOVERAGEPERIODID = ECP.ID AND
																				ET.ID = (SELECT MAX(ET2.ID) FROM SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTTRANS ET2 WHERE ET2.ENROLLMENTCOVERAGEPERIODID = ECP.ID))
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTPCMPOLICY PCM ON			(	PCM.ENROLLMENTTRANSID = ET.ID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTASSETLIST EAL ON			(	ET.ID = EAL.ENROLLMENTTRANSID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTASSETLISTFACTOR EALF ON	(	EALF.ENROLLMENTASSETLISTID = EAL.ID AND
																				EALF.PCMCONTAINERID = PCM.PCMCONTAINERID AND
																				EALF.PCMPOLICYSCHEMAID = PCM.PCMPOLICYSCHEMAID AND
																				EALF.PCMPOLICYID = PCM.PCMPOLICYID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICY POL ON								(	PCM.PCMPOLICYID = POL.ID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYINSURED POI ON						(	POL.INSUREDID = POI.ID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP ON						(	POL.ID = PP.POLICYID AND
																				PP.ID IN (SELECT MAX(PP2.ID) FROM SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP2 WHERE PP2.POLICYID = POL.ID))
INNER JOIN	SESHOSTPRODCOPY.DBO.NAICTYPE CARR ON							(	CARR.ID = POL.CARRIERID)
INNER JOIN  SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH ON							(	SCH.POLICYID = PCM.PCMPOLICYID AND
																				SCH.ID = PCM.PCMPOLICYSCHEMAID)
INNER JOIN  SESHOSTPRODCOPY.DBO.MASTERPRODUCT PROD ON						(	PROD.ID = SCH.PRODUCTID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMACOVERAGEFACTOR PSCOVF ON		(	PSCOVF.COVERAGEFACTORHEADERID = EALF.PCMHEADERID AND 
																				PSCOVF.MASTERFACTORID = EALF.PCMFACTORID AND 
																				PSCOVF.USAGECODEID = EALF.PCMUSAGECODEID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMACONTAINERFACTOR PSCONF ON		(	PSCONF.CONTAINERFACTORHEADERID = EALF.PCMHEADERID AND
																				PSCONF.MASTERFACTORID = EALF.PCMFACTORID AND 
																				PSCONF.USAGECODEID = EALF.PCMUSAGECODEID)
WHERE EALF.PCMUSAGECODEID IS NOT NULL
GROUP BY 
	EC.ID,
	POL.APPLICATIONUSAGEID,
	PROD.CODE,
	ECU.CUSTOMERNAME,
	ECU.ADDRESS1+(CASE WHEN ECU.ADDRESS2 IS NULL THEN '' ELSE (' '+ECU.ADDRESS2) END),
	ECU.CITY,
	ECU.STATE,
	ECU.POSTALCODE,
	POI.CITY,
	POI.STATEPROVINCE,
	POI.POSTALCODE,
	ECU.CUSTOMERPHONE,
	ECU.CUSTOMEREMAILADDRESS,
	CAST(ECU.DATECREATED AS DATE),
	CAST(ECU.UPDATED AS DATE),
	EC.CONTRACTNUMBER,
	ECP.COVERAGEPERIOD,
	CAST(EC.DATECREATED AS DATE),
	CAST(EC.UPDATED AS DATE),
	POL.POLICYNUMBER,
	POL.PEOPLESOFTCLIENTNUMBER,
	CAST(E.DATECREATED AS DATE),
	CAST(E.UPDATED AS DATE),
	CAST(ECP.COVERAGESTARTDATE AS DATE),
	CAST(ECP.COVERAGEENDDATE AS DATE),
	CAST(ECP.DATECREATED AS DATE),
	CAST(ECP.UPDATED AS DATE),		
	ET.ID,
	ET.BILLINGFREQUENCY,
	EALF.PCMUSAGECODEID,
	PSCOVF.NAME,
	PSCONF.NAME,
	CARR.NAME,
	CARR.DESCRIPTION,
	CAST(PP.PRMCODE AS INT)

UNION

SELECT	A.POLICYNUMBER 'POL_NUM',
		'BAM' 'SYSTEM',
		A.RENTALREFERENCEID 'CONTRACT_NUM',
		A.ID 'CONTRACT_ID',
		BCP.ID 'ENROLL_TRAN',
		POL.PEOPLESOFTCLIENTNUMBER 'PS_NUM',
		BA.RENTALSTARTDATE 'COV_START',
		BA.RENTALENDDATE 'COV_END',
		'ACTUAL CASH VALUE' 'SETTLEMENT',
		PROD.CODE 'PRODUCT',
		A.CUSTOMERNAME 'CUSTOMER_NAME',
		A.ADDRESSLINE1+(CASE WHEN A.ADDRESSLINE2 IS NULL THEN '' ELSE (' '+A.ADDRESSLINE2) END) 'CUSTOMER_ADD',
		A.CITY 'CUSTOMER_CITY',
		A.STATE 'CUSTOMER_STATE',
		A.ZIP 'CUSTOMER_ZIP',
		PI.CITY 'INSURED_CITY',
		PI.STATEPROVINCE 'INSURED_STATE',
		PI.POSTALCODE 'INSURED_ZIP',
		'' 'CUSTOMER_PHONE',
		'' 'CUSTOMER_EMAIL',
		1 'COVERAGE_PERIOD',
		A.CREATED 'CUSTOMER_CREATE',
		A.CREATED 'CUSTOMER_EDIT',
		A.CREATED 'CONTRACT_CREATE',
		A.CREATED 'CONTRACT_EDIT',
		A.CREATED 'ENROLL_CREATE',
		A.CREATED 'ENROLL_EDIT',
		A.CREATED 'COV_CREATE',
		A.CREATED 'COV_EDIT',
		CARR.NAME 'CARR_ABBR',
		CARR.DESCRIPTION 'CARR_NAME',
		PP.PRMCODE 'PRODUCER_CODE'

FROM SESBATCHPRODCOPY.DBO.BAMENROLLMENT A			
INNER JOIN SESBATCHPRODCOPY.DBO.BAMCOVERAGEPERIOD BCP ON (BCP.ENROLLMENTID = A.ID AND BCP.RENTALENDDATE >GETDATE())			
INNER JOIN SESBATCHPRODCOPY.DBO.BAMASSET BA ON (BA.COVERAGEPERIODID = BCP.ID)			
INNER JOIN SESHOSTPRODCOPY.DBO.POLICY POL ON (POL.POLICYNUMBER = A.POLICYNUMBER)			
INNER JOIN SESHOSTPRODCOPY.DBO.POLICYINSURED PI ON (POL.INSUREDID = PI.ID)			
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP ON (POL.ID = PP.POLICYID AND PP.ID IN (SELECT MAX(PP2.ID) FROM SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP2 WHERE PP2.POLICYID = POL.ID))
INNER JOIN	SESHOSTPRODCOPY.DBO.NAICTYPE CARR ON (CARR.ID = POL.CARRIERID)
INNER JOIN SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH ON (SCH.POLICYID = POL.ID AND SCH.ID IN (SELECT MAX(SCH2.ID) FROM SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH2 WHERE SCH2.POLICYID = POL.ID))			
INNER JOIN SESHOSTPRODCOPY.DBO.MASTERPRODUCT PROD ON (PROD.ID = SCH.PRODUCTID)			
WHERE PP.PRMCODE IN ('199257', '569237','573389','247864')

UNION

SELECT	A.POLICYNUMBER 'POL_NUM',
		'BAM' 'SYSTEM',
		A.RENTALREFERENCEID 'CONTRACT_NUM',
		A.ID 'CONTRACT_ID',
		BCP.ID 'ENROLL_TRAN',
		POL.PEOPLESOFTCLIENTNUMBER 'PS_NUM',
		BA.RENTALSTARTDATE 'COV_START',
		BA.RENTALENDDATE 'COV_END',
		'ACTUAL CASH VALUE' 'SETTLEMENT',
		PROD.CODE 'PRODUCT',
		A.CUSTOMERNAME 'CUSTOMER_NAME',
		A.ADDRESSLINE1+(CASE WHEN A.ADDRESSLINE2 IS NULL THEN '' ELSE (' '+A.ADDRESSLINE2) END) 'CUSTOMER_ADD',
		A.CITY 'CUSTOMER_CITY',
		A.STATE 'CUSTOMER_STATE',
		A.ZIP 'CUSTOMER_ZIP',
		PI.CITY 'INSURED_CITY',
		PI.STATEPROVINCE 'INSURED_STATE',
		PI.POSTALCODE 'INSURED_ZIP',
		'' 'CUSTOMER_PHONE',
		'' 'CUSTOMER_EMAIL',
		1 'COVERAGE_PERIOD',
		A.CREATED 'CUSTOMER_CREATE',
		A.CREATED 'CUSTOMER_EDIT',
		A.CREATED 'CONTRACT_CREATE',
		A.CREATED 'CONTRACT_EDIT',
		A.CREATED 'ENROLL_CREATE',
		A.CREATED 'ENROLL_EDIT',
		A.CREATED 'COV_CREATE',
		A.CREATED 'COV_EDIT',
		CARR.NAME 'CARR_ABBR',
		CARR.DESCRIPTION 'CARR_NAME',
		PP.PRMCODE 'PRODUCER_CODE'

FROM SESBATCHPRODCOPY.DBO.BAMENROLLMENT A			
INNER JOIN SESBATCHPRODCOPY.DBO.BAMCOVERAGEPERIOD BCP ON (BCP.ENROLLMENTID = A.ID AND BCP.RENTALENDDATE >GETDATE())			
INNER JOIN SESBATCHPRODCOPY.DBO.BAMASSET BA ON (BA.COVERAGEPERIODID = BCP.ID)			
INNER JOIN SESHOSTPRODCOPY.DBO.POLICY POL ON (POL.POLICYNUMBER = A.POLICYNUMBER)			
INNER JOIN SESHOSTPRODCOPY.DBO.POLICYINSURED PI ON (POL.INSUREDID = PI.ID)			
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP ON (POL.ID = PP.POLICYID AND PP.ID IN (SELECT MAX(PP2.ID) FROM SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP2 WHERE PP2.POLICYID = POL.ID))
INNER JOIN	SESHOSTPRODCOPY.DBO.NAICTYPE CARR ON (CARR.ID = POL.CARRIERID)
INNER JOIN SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH ON (SCH.POLICYID = POL.ID AND SCH.ID IN (SELECT MAX(SCH2.ID) FROM SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH2 WHERE SCH2.POLICYID = POL.ID))			
INNER JOIN SESHOSTPRODCOPY.DBO.MASTERPRODUCT PROD ON (PROD.ID = SCH.PRODUCTID AND PROD.CODE = '2310')

UNION

--ACTIVE IN SED--
SELECT DISTINCT
	POL.POLICYNUMBER 'POL_NUM',
	CASE WHEN POL.APPLICATIONUSAGEID = '1' THEN 'BAM'
		WHEN POL.APPLICATIONUSAGEID = '2' THEN 'QIPS'
		WHEN POL.APPLICATIONUSAGEID = '3' THEN 'VES'
		WHEN POL.APPLICATIONUSAGEID = '4' THEN 'SED' END AS 'SYSTEM',
	EC.CONTRACTNUMBER 'CONTRACT_NUM',
	EC.ID 'CONTRACT_ID',
	ET.ID 'ENROLL_TRAN',
	POL.PEOPLESOFTCLIENTNUMBER 'PS_NUM',
	CAST(ECP.COVERAGESTARTDATE AS DATE) 'COV_START',
	CAST(ECP.COVERAGEENDDATE AS DATE) 'COV_END',
	CASE	WHEN EALF.PCMUSAGECODEID = '128' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME 
			WHEN EALF.PCMUSAGECODEID = '128' AND PSCONF.NAME IS NOT NULL THEN PSCONF.NAME 
			WHEN EALF.PCMUSAGECODEID = '32' AND PSCOVF.NAME IS NOT NULL THEN PSCOVF.NAME ELSE NULL END 'SETTLEMENT',
	CAST(	PROD.CODE AS INT) 'PRODUCT',
	ECU.CUSTOMERNAME 'CUSTOMER_NAME',
	ECU.ADDRESS1+(CASE WHEN ECU.ADDRESS2 IS NULL THEN '' ELSE (' '+ECU.ADDRESS2) END) 'CUSTOMER_ADD',
	ECU.CITY 'CUSTOMER_CITY',
	ECU.STATE 'CUSTOMER_STATE',
	ECU.POSTALCODE 'CUSTOMER_ZIP',
	CASE WHEN PROD.CODE = '2310' THEN ECU.CITY WHEN PROD.CODE = '2301' THEN ECU.CITY ELSE POI.CITY END 'INSURED_CITY',
	CASE WHEN PROD.CODE = '2310' THEN ECU.STATE  WHEN PROD.CODE = '2301' THEN ECU.STATE ELSE POI.STATEPROVINCE END 'INSURED_STATE',
	CASE WHEN PROD.CODE = '2310' THEN ECU.POSTALCODE  WHEN PROD.CODE = '2301' THEN ECU.POSTALCODE ELSE POI.POSTALCODE END 'INSURED_ZIP',
	ECU.CUSTOMERPHONE 'CUSTOMER_PHONE',
	ECU.CUSTOMEREMAILADDRESS 'CUSTOMER_EMAIL',
	ECP.COVERAGEPERIOD 'COVERAGE_PERIOD',
	CAST(ECU.DATECREATED AS DATE) 'CUSTOMER_CREATE',
	CAST(ECU.UPDATED AS DATE) 'CUSTOMER_EDIT',
	CAST(EC.DATECREATED AS DATE) 'CONTRACT_CREATE',
	CAST(EC.UPDATED AS DATE) 'CONTRACT_EDIT',
	CAST(E.DATECREATED AS DATE) 'ENROLL_CREATE',
	CAST(E.UPDATED AS DATE) 'ENROLL_EDIT',
	CAST(ECP.DATECREATED AS DATE) 'COV_CREATE',
	CAST(ECP.UPDATED AS DATE) 'COV_EDIT',
	CARR.NAME 'CARR_ABBR',
	CARR.DESCRIPTION 'CARR_NAME',
	CAST(PP.PRMCODE AS INT) 'PRODUCER_CODE'

FROM		SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENT E
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCONTRACT EC ON			(	E.ENROLLMENTCONTRACTID = EC.ID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCUSTOMER ECU ON			(	E.ENROLLMENTCUSTOMERID = ECU.ID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP ON	(	E.ID = ECP.ENROLLMENTID AND
																				ECP.ID = (SELECT MAX(ECP2.ID) FROM SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTCOVERAGEPERIOD ECP2 WHERE ECP2.ENROLLMENTID = E.ID) AND
																				ECP.COVERAGEENDDATE > GETDATE())
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTTRANS ET ON				(	ET.ENROLLMENTCOVERAGEPERIODID = ECP.ID AND
																				ET.ID = (SELECT MAX(ET2.ID) FROM SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTTRANS ET2 WHERE ET2.ENROLLMENTCOVERAGEPERIODID = ECP.ID))
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTPCMPOLICY PCM ON			(	PCM.ENROLLMENTTRANSID = ET.ID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTASSETLIST EAL ON			(	ET.ID = EAL.ENROLLMENTTRANSID)
INNER JOIN	SESENROLLMENTAPIPRODCOPY.DBO.ENROLLMENTASSETLISTFACTOR EALF ON	(	EALF.ENROLLMENTASSETLISTID = EAL.ID AND
																				EALF.PCMCONTAINERID = PCM.PCMCONTAINERID AND
																				EALF.PCMPOLICYSCHEMAID = PCM.PCMPOLICYSCHEMAID AND
																				EALF.PCMPOLICYID = PCM.PCMPOLICYID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICY POL ON								(	PCM.PCMPOLICYID = POL.ID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYINSURED POI ON						(	POL.INSUREDID = POI.ID)
INNER JOIN	SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP ON						(	POL.ID = PP.POLICYID AND
																				PP.ID IN (SELECT MAX(PP2.ID) FROM SESHOSTPRODCOPY.DBO.POLICYPRODUCER PP2 WHERE PP2.POLICYID = POL.ID))
INNER JOIN	SESHOSTPRODCOPY.DBO.NAICTYPE CARR ON							(	CARR.ID = POL.CARRIERID)
INNER JOIN  SESHOSTPRODCOPY.DBO.POLICYSCHEMA SCH ON							(	SCH.POLICYID = PCM.PCMPOLICYID AND
																				SCH.ID = PCM.PCMPOLICYSCHEMAID)
INNER JOIN  SESHOSTPRODCOPY.DBO.MASTERPRODUCT PROD ON						(	PROD.ID = SCH.PRODUCTID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMACOVERAGEFACTOR PSCOVF ON		(	PSCOVF.COVERAGEFACTORHEADERID = EALF.PCMHEADERID AND 
																				PSCOVF.MASTERFACTORID = EALF.PCMFACTORID AND 
																				PSCOVF.USAGECODEID = EALF.PCMUSAGECODEID)
LEFT JOIN	SESHOSTPRODCOPY.DBO.POLICYSCHEMACONTAINERFACTOR PSCONF ON		(	PSCONF.CONTAINERFACTORHEADERID = EALF.PCMHEADERID AND
																				PSCONF.MASTERFACTORID = EALF.PCMFACTORID AND 
																				PSCONF.USAGECODEID = EALF.PCMUSAGECODEID)
WHERE EALF.PCMUSAGECODEID IS NOT NULL
GROUP BY 
	EC.ID,
	POL.APPLICATIONUSAGEID,
	PROD.CODE,
	ECU.CUSTOMERNAME,
	ECU.ADDRESS1+(CASE WHEN ECU.ADDRESS2 IS NULL THEN '' ELSE (' '+ECU.ADDRESS2) END),
	ECU.CITY,
	ECU.STATE,
	ECU.POSTALCODE,
	POI.CITY,
	POI.STATEPROVINCE,
	POI.POSTALCODE,
	ECU.CUSTOMERPHONE,
	ECU.CUSTOMEREMAILADDRESS,
	CAST(ECU.DATECREATED AS DATE),
	CAST(ECU.UPDATED AS DATE),
	EC.CONTRACTNUMBER,
	ECP.COVERAGEPERIOD,
	CAST(EC.DATECREATED AS DATE),
	CAST(EC.UPDATED AS DATE),
	POL.POLICYNUMBER,
	POL.PEOPLESOFTCLIENTNUMBER,
	CAST(E.DATECREATED AS DATE),
	CAST(E.UPDATED AS DATE),
	CAST(ECP.COVERAGESTARTDATE AS DATE),
	CAST(ECP.COVERAGEENDDATE AS DATE),
	CAST(ECP.DATECREATED AS DATE),
	CAST(ECP.UPDATED AS DATE),		
	ET.ID,
	ET.BILLINGFREQUENCY,
	EALF.PCMUSAGECODEID,
	PSCOVF.NAME,
	PSCONF.NAME,
	CARR.NAME,
	CARR.DESCRIPTION,
	CAST(PP.PRMCODE AS INT)